remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # Add this line to the plugins list if you already have one
title: Kenvue Global Data Layer Standard | Google Analytics 4
description: Kenvue's global Data Layer architecture is to be used on all sites to properly support all GA4 implementations.
