remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # Add this line to the plugins list if you already have one
title: Kenvue Global Data Layer Standard | Google Analytics 4
description: Kenvue's global Data Layer architecture is required to be implemented to support Google Analyticds 4.
  sublinks:
    - title: Add Payment Info
      url: /events/ecommerce/add_payment_info
    - title: Add Shipping Info
      url: /events/ecommerce/add_shipping_info
