site_name: Kenvue Marketing Analytics Data Layer Schema | GA4
repo_url: https://github.com/Kenvue-cbi-digitalanalytics/client-kenvue-ga4-dl-spec
repo_name: Kenvue-cbi-digitalanalytics/client-kenvue-ga4-dl-spec
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: teal
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - git-revision-date-localized
dev_addr: '0.0.0.0:8080'
