site_name: Kenvue Marketing Analytics Data Layer Schema
repo_url: https://github.com/searchdiscovery/client-kenvue-ga4-dl-spec
repo_name: searchdiscovery/client-kenvue-ga4-dl-spec
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: indigo
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
markdown_extensions:
  - admonition
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - git-revision-date
  - encryptcontent:
      global_password: 'kenvue2023' # TODO: switch to environment variable
dev_addr: '0.0.0.0:8080'
